name: profile-mw
services:
  joomla:
    container_name: mw-app
    image: joomla:4.4.11-php8.2-apache
    restart: always
    ports:
      - 8080:80
    environment:
      - JOOMLA_DB_HOST=joomladb
      - JOOMLA_DB_PASSWORD=example
    depends_on:
      joomladb:
        condition: service_healthy
    user: 1000:1000
    volumes:
      - ./site_joomla:/var/www/html

  joomladb:
    container_name: mw-db
    image: mysql:8.0.13
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
    healthcheck:    
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    user: 1000:1000
    volumes:
      - ./db:/var/lib/mysql